name: CI
on: [push, pull_request]
jobs:
   arch:
      runs-on: ubuntu-latest
      container: archlinux:latest
      steps:
         - run: pacman --noconfirm --noprogressbar -Syu
         - run: pacman --noconfirm --noprogressbar -S make go asciidoc gcc
         - uses: actions/checkout@v1
         - run: make
         - run: make test
         - run: GOBIN=/usr/bin make deps lint
   void:
      runs-on: ubuntu-latest
      container: voidlinux/voidlinux-musl
      steps:
         # update xbps, if necessary
         - run: xbps-install -Syu || ( xbps-install -yu xbps && xbps-install -yu )
         - run: xbps-install -y make go asciidoc gcc
         - uses: actions/checkout@v1
         - run: make
         - run: make test
         - run: GOBIN=/usr/bin make deps lint
